import { supabaseAdmin } from "../../lib/adminSupabase";
import { VendorFormValues } from "../../types/schema/vendor.schema";

export async function addVendor(form: VendorFormValues) {
  const email = (form.email ?? "").trim();
  const password = form.password ?? "";
  const shouldCreateAuthUser = email.length > 0 && password.length > 0;

  const roleId = "7cfabb14-ee17-48bc-b03f-4199ef32d1e0";

  // 1) Create auth user only if email + password exist
  let authUserId: string | null = null;

  if (shouldCreateAuthUser) {
    const { data: userData, error: userError } =
      await supabaseAdmin.auth.admin.createUser({
        email,
        password,
        email_confirm: true,
        user_metadata: {
          firstName: form.vendor_name,
          lastName: (form.contact_name ?? "").trim() || null,
          phone: (form.phone_number ?? "").trim() || null,
          roleId,
        },
      });

    if (userError) {
      console.error("Error creating auth user:", userError);
      return {
        success: false,
        error: userError,
        message: "فشل في إنشاء المستخدم",
      };
    }

    authUserId = userData.user?.id ?? null;
    if (!authUserId) {
      return {
        success: false,
        error: new Error("No user id returned from auth.createUser"),
        message: "فشل في إنشاء المستخدم - معرف المستخدم غير متاح",
      };
    }
  }

  // 2) Insert vendor row (id generated by table), link user_id if exists
  const { data: vendorRow, error: vendorErr } = await supabaseAdmin
    .from("vendors")
    .insert({
      vendor_name: form.vendor_name,
      specialization_id: form.specialization_id, // ❗ only if you actually have this column (see note below)
      contact_name: (form.contact_name ?? "").trim() || null,
      email: email || null,
      phone_number: (form.phone_number ?? "").trim() || null,
      alt_phone_number: (form.alt_phone_number ?? "").trim() || null,
      country: (form.country ?? "").trim() || null,
      city: (form.city ?? "").trim() || null,
      address: (form.address ?? "").trim() || null,
      user_id: authUserId,
    })
    .select("id,user_id")
    .single();

  if (vendorErr) {
    console.error("Error inserting vendor:", vendorErr);
    return {
      success: false,
      error: vendorErr,
      message: "فشل في إنشاء البائع",
    };
  }

  // 3) role + specialization only if auth user exists
  if (authUserId) {
    const { error: userRoleError } = await supabaseAdmin
      .from("user_roles")
      .insert({
        role_id: roleId,
        user_id: authUserId,
      });

    if (userRoleError) {
      console.error("Error inserting user role data:", userRoleError);
      return {
        success: false,
        error: userRoleError,
        message: "فشل في تعيين دور المستخدم",
      };
    }

    const { error: userSpecError } = await supabaseAdmin
      .from("user_specializations")
      .insert({
        specialization_id: form.specialization_id,
        user_id: authUserId,
      });

    if (userSpecError) {
      console.error("Error inserting user specialization data:", userSpecError);
      return {
        success: false,
        error: userSpecError,
        message: "فشل في تعيين تخصص المستخدم",
      };
    }
  }

  return {
    success: true,
    message: authUserId
      ? "تم إنشاء البائع (مع حساب دخول) بنجاح"
      : "تم إنشاء البائع بنجاح (بدون حساب دخول)",
    vendorId: vendorRow.id,
    authUserId,
  };
}
