// =====================================================================
// Phase 1 / Phase 2 schema types — HAND-WRITTEN, TEMPORARY
// =====================================================================
//
// WHY THIS FILE EXISTS
//   src/lib/supabase.ts is generated by `npm run types` and does NOT
//   yet contain any of the tables Phase 1 created, or the functions
//   Phase 2 created. Until someone re-runs the generator, the typed
//   supabase client rejects `.from("departments")` at compile time.
//
//   Rather than loosen the main client (which would remove type safety
//   from the whole app), this file describes just the new surface and
//   src/lib/permissionsDb.ts exposes a separately-typed client for it.
//
// WHEN TO DELETE THIS FILE
//   After `npm run types` is re-run post-Phase-1. At that point every
//   table below appears in the generated Database type, permissionsDb
//   can be replaced by the ordinary `supabase` client, and this file
//   goes away. It is deliberately kept small so that swap is easy.
//
//   Keep it in sync with phase1-schema.sql until then. If the two ever
//   disagree, phase1-schema.sql is the truth.
// =====================================================================

/** phase1-schema.sql section 1 */
export type PartyType = "company" | "vendor" | "contractor" | "client";

/**
 * phase1-schema.sql section 1.
 * Only meaningful for permissions where is_project_scoped = true.
 */
export type GrantScope = "all_projects" | "team_projects_only";

/** permission_catalog.area — the CHECK constraint allows exactly these five. */
export type PermissionArea =
  | "Admin"
  | "Project"
  | "Finance"
  | "HR"
  | "Operations";

/**
 * Which layer of the ladder answered. Mirrors the source_layer values
 * returned by resolve_permission_ladder() in phase2-resolver.sql.
 */
export type SourceLayer =
  | "team_member_override"
  | "project_default"
  | "user_override"
  | "department_baseline"
  | "role_baseline"
  | "default_deny"
  | "ineligible"
  | "no_project_context";

// NOTE ON `type` VS `interface` BELOW — do not "tidy" these into
// interfaces. postgrest-js requires every Row/Insert/Update to satisfy
// Record<string, unknown>. A TypeScript interface does NOT satisfy that
// (interfaces get no implicit index signature); a type alias does. Using
// `interface` here makes the whole schema fail the GenericSchema
// constraint, at which point every table silently resolves to `never`
// and every query in these hooks stops typechecking.

export type PermissionCatalogRow = {
  id: string;
  name: string;
  area: PermissionArea;
  description: string;
  is_project_scoped: boolean;
  parent_permission_id: string | null;
  is_active: boolean;
};

export type DepartmentRow = {
  id: string;
  name: string;
  name_ar: string | null;
  code: string;
  is_active: boolean;
};

export type RolePermissionGrantRow = {
  role_id: string;
  permission_id: string;
  allowed: boolean;
  scope: GrantScope;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

export type DepartmentPermissionGrantRow = {
  department_id: string;
  permission_id: string;
  allowed: boolean;
  scope: GrantScope;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

export type UserPermissionGrantRow = {
  user_id: string;
  permission_id: string;
  allowed: boolean;
  scope: GrantScope;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

/** One row of effective_permissions() / my_effective_permissions(). */
export type EffectivePermissionRow = {
  permission_name: string;
  area: PermissionArea;
  is_project_scoped: boolean;
  allowed: boolean;
  source_layer: SourceLayer;
};

// ---------------------------------------------------------------------
// The Database-shaped type the scoped client is instantiated with.
// Only what Phase 3 touches is listed. Adding a table here does not
// make it exist — check phase1-schema.sql first.
// ---------------------------------------------------------------------
export type PermissionsDatabase = {
  // Mirrors the shape of the generated Database type in src/lib/supabase.ts.
  // supabase-js keys its generics off __InternalSupabase; without it every
  // table resolves to `never` and nothing typechecks.
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      departments: {
        Row: DepartmentRow;
        Insert: {
          id?: string;
          name: string;
          name_ar?: string | null;
          code: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          name_ar?: string | null;
          code?: string;
          is_active?: boolean;
        };
        Relationships: [];
      };
      permission_catalog: {
        Row: PermissionCatalogRow;
        // Seeded by phase1-schema.sql. The app reads it and never writes it,
        // but the shapes have to be real object types or inference breaks.
        Insert: {
          id?: string;
          name: string;
          area: PermissionArea;
          description: string;
          is_project_scoped: boolean;
          parent_permission_id?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          area?: PermissionArea;
          description?: string;
          is_project_scoped?: boolean;
          parent_permission_id?: string | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      role_permission_grants: {
        Row: RolePermissionGrantRow;
        Insert: {
          role_id: string;
          permission_id: string;
          allowed: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          role_id?: string;
          permission_id?: string;
          allowed?: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      department_permission_grants: {
        Row: DepartmentPermissionGrantRow;
        Insert: {
          department_id: string;
          permission_id: string;
          allowed: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          department_id?: string;
          permission_id?: string;
          allowed?: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      user_permission_grants: {
        Row: UserPermissionGrantRow;
        Insert: {
          user_id: string;
          permission_id: string;
          allowed: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          user_id?: string;
          permission_id?: string;
          allowed?: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      // Only the three columns Phase 3 touches. This is a narrowed view of
      // the real employees table, not a redefinition of it — the ordinary
      // typed client still sees the full row.
      employees: {
        Row: {
          id: string;
          department_id: string | null;
          specializations_id: string | null;
        };
        Insert: {
          id: string;
          department_id?: string | null;
          specializations_id?: string | null;
        };
        Update: {
          id?: string;
          department_id?: string | null;
          specializations_id?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      effective_permissions: {
        Args: { p_user_id: string; p_project_id?: string | null };
        Returns: EffectivePermissionRow[];
      };
      can_do: {
        Args: {
          p_user_id: string;
          p_permission_name: string;
          p_project_id?: string | null;
        };
        Returns: boolean;
      };
    };
    Enums: {
      party_type_enum: PartyType;
      grant_scope_enum: GrantScope;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
