// =====================================================================
// Phase 1 / Phase 2 schema types — HAND-WRITTEN, TEMPORARY
// =====================================================================
//
// SCOPE NOTE (added in Phase 4): despite the file name, this now covers
// every table the Phase 1 migration added that the app talks to — the
// permission layers AND team_assignments. Keeping one hand-written
// schema means one thing to delete when the generator is re-run, rather
// than two.
//
// WHY THIS FILE EXISTS
//   src/lib/supabase.ts is generated by `npm run types` and does NOT
//   yet contain any of the tables Phase 1 created, or the functions
//   Phase 2 created. Until someone re-runs the generator, the typed
//   supabase client rejects `.from("departments")` at compile time.
//
//   Rather than loosen the main client (which would remove type safety
//   from the whole app), this file describes just the new surface and
//   src/lib/permissionsDb.ts exposes a separately-typed client for it.
//
// WHEN TO DELETE THIS FILE
//   After `npm run types` is re-run post-Phase-1. At that point every
//   table below appears in the generated Database type, permissionsDb
//   can be replaced by the ordinary `supabase` client, and this file
//   goes away. It is deliberately kept small so that swap is easy.
//
//   Keep it in sync with phase1-schema.sql until then. If the two ever
//   disagree, phase1-schema.sql is the truth.
// =====================================================================

/** phase1-schema.sql section 1 */
export type PartyType = "company" | "vendor" | "contractor" | "client";

/**
 * phase1-schema.sql section 1.
 * Only meaningful for permissions where is_project_scoped = true.
 */
export type GrantScope = "all_projects" | "team_projects_only";

/** permission_catalog.area — the CHECK constraint allows exactly these five. */
export type PermissionArea =
  | "Admin"
  | "Project"
  | "Finance"
  | "HR"
  | "Operations";

/**
 * Which layer of the ladder answered. Mirrors the source_layer values
 * returned by resolve_permission_ladder() in phase2-resolver.sql.
 */
export type SourceLayer =
  | "team_member_override"
  | "project_default"
  | "user_override"
  | "department_baseline"
  | "role_baseline"
  | "default_deny"
  | "ineligible"
  | "no_project_context";

// NOTE ON `type` VS `interface` BELOW — do not "tidy" these into
// interfaces. postgrest-js requires every Row/Insert/Update to satisfy
// Record<string, unknown>. A TypeScript interface does NOT satisfy that
// (interfaces get no implicit index signature); a type alias does. Using
// `interface` here makes the whole schema fail the GenericSchema
// constraint, at which point every table silently resolves to `never`
// and every query in these hooks stops typechecking.

export type PermissionCatalogRow = {
  id: string;
  name: string;
  area: PermissionArea;
  description: string;
  is_project_scoped: boolean;
  parent_permission_id: string | null;
  is_active: boolean;
};

export type DepartmentRow = {
  id: string;
  name: string;
  name_ar: string | null;
  code: string;
  is_active: boolean;
};

export type RolePermissionGrantRow = {
  role_id: string;
  permission_id: string;
  allowed: boolean;
  scope: GrantScope;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

export type DepartmentPermissionGrantRow = {
  department_id: string;
  permission_id: string;
  allowed: boolean;
  scope: GrantScope;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

export type UserPermissionGrantRow = {
  user_id: string;
  permission_id: string;
  allowed: boolean;
  scope: GrantScope;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

/**
 * phase1-schema.sql section 8. Who works on a project and in what
 * project role. No financial data — percentages live in
 * project_distributions and are Phase 5's business, not this table's.
 *
 * person_id references employees.id, which is the same value as
 * users.id (1:1 FK). The old project_assignments column was called
 * user_id while pointing at employees — this rename fixes that footgun.
 */
export type TeamAssignmentRow = {
  id: string;
  project_id: string;
  person_id: string;
  project_role_id: string;
  assigned_at: string;
  assigned_by: string | null;
};

export type ProjectRoleRow = {
  id: string;
  name: string;
};

/**
 * phase1-schema.sql section 9. What share of a project a person
 * receives. UNIQUE (project_id, person_id) — one row per person per
 * project, which is the structural fix for the old table's
 * "delete by (project, person) hits several rows" bug.
 *
 * Deliberately currency-agnostic: one percentage per person per
 * project. The old editor presents a per-currency grid but stores a
 * single shared column, so nothing is lost by being honest about it.
 */
export type ProjectDistributionRow = {
  id: string;
  project_id: string;
  person_id: string;
  percentage: number;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
};

/**
 * phase1-schema.sql section 8, layer 2. "Everyone on this project."
 * Applies to every current AND future team member — that automatic
 * inheritance is the entire reason the layer exists (guide section 4.6).
 *
 * NO SCOPE COLUMN, deliberately: the row is already attached to one
 * specific project, so "all projects / team projects only" is a question
 * that cannot arise here. Only the three company-wide layers carry it.
 */
export type ProjectPermissionDefaultRow = {
  project_id: string;
  permission_id: string;
  allowed: boolean;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

/**
 * phase1-schema.sql section 8, layer 1 — the most specific layer, which
 * beats every other. "This one person, on this one project."
 *
 * Keyed on users.id, NOT employees.id, even though team membership is
 * keyed on employees.id. The two are the same value (1:1 FK); keeping
 * every permission table on users.id removes a class of "which id is
 * this?" bug. Also no scope column, for the same reason as above.
 */
export type TeamMemberPermissionGrantRow = {
  project_id: string;
  user_id: string;
  permission_id: string;
  allowed: boolean;
  granted_by: string | null;
  granted_at: string;
  note: string | null;
};

/** One row of effective_permissions() / my_effective_permissions(). */
export type EffectivePermissionRow = {
  permission_name: string;
  area: PermissionArea;
  is_project_scoped: boolean;
  allowed: boolean;
  source_layer: SourceLayer;
};

// ---------------------------------------------------------------------
// The Database-shaped type the scoped client is instantiated with.
// Only what Phase 3 touches is listed. Adding a table here does not
// make it exist — check phase1-schema.sql first.
// ---------------------------------------------------------------------
export type PermissionsDatabase = {
  // Mirrors the shape of the generated Database type in src/lib/supabase.ts.
  // supabase-js keys its generics off __InternalSupabase; without it every
  // table resolves to `never` and nothing typechecks.
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      departments: {
        Row: DepartmentRow;
        Insert: {
          id?: string;
          name: string;
          name_ar?: string | null;
          code: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          name_ar?: string | null;
          code?: string;
          is_active?: boolean;
        };
        Relationships: [];
      };
      permission_catalog: {
        Row: PermissionCatalogRow;
        // Seeded by phase1-schema.sql. The app reads it and never writes it,
        // but the shapes have to be real object types or inference breaks.
        Insert: {
          id?: string;
          name: string;
          area: PermissionArea;
          description: string;
          is_project_scoped: boolean;
          parent_permission_id?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          area?: PermissionArea;
          description?: string;
          is_project_scoped?: boolean;
          parent_permission_id?: string | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      role_permission_grants: {
        Row: RolePermissionGrantRow;
        Insert: {
          role_id: string;
          permission_id: string;
          allowed: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          role_id?: string;
          permission_id?: string;
          allowed?: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      department_permission_grants: {
        Row: DepartmentPermissionGrantRow;
        Insert: {
          department_id: string;
          permission_id: string;
          allowed: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          department_id?: string;
          permission_id?: string;
          allowed?: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      user_permission_grants: {
        Row: UserPermissionGrantRow;
        Insert: {
          user_id: string;
          permission_id: string;
          allowed: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          user_id?: string;
          permission_id?: string;
          allowed?: boolean;
          scope?: GrantScope;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      project_permission_defaults: {
        Row: ProjectPermissionDefaultRow;
        Insert: {
          project_id: string;
          permission_id: string;
          allowed: boolean;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          project_id?: string;
          permission_id?: string;
          allowed?: boolean;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      team_member_permission_grants: {
        Row: TeamMemberPermissionGrantRow;
        Insert: {
          project_id: string;
          user_id: string;
          permission_id: string;
          allowed: boolean;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Update: {
          project_id?: string;
          user_id?: string;
          permission_id?: string;
          allowed?: boolean;
          granted_by?: string | null;
          granted_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      // Narrowed, read-only view. users.party_type was added by Phase 1
      // and is not in the generated types yet, so any query that filters
      // or selects it has to come through this client.
      users: {
        Row: {
          id: string;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          party_type: PartyType;
        };
        // Real object shapes, not `never`: postgrest-js needs every
        // Row/Insert/Update to satisfy Record<string, unknown>, and
        // `never` makes the whole schema fail that constraint — at which
        // point every table silently resolves to `never`. The app never
        // writes users through this client regardless.
        Insert: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          party_type?: PartyType;
        };
        Update: {
          id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          party_type?: PartyType;
        };
        Relationships: [];
      };
      project_distributions: {
        Row: ProjectDistributionRow;
        Insert: {
          id?: string;
          project_id: string;
          person_id: string;
          percentage: number;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          person_id?: string;
          percentage?: number;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      team_assignments: {
        Row: TeamAssignmentRow;
        Insert: {
          id?: string;
          project_id: string;
          person_id: string;
          project_role_id: string;
          assigned_at?: string;
          assigned_by?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          person_id?: string;
          project_role_id?: string;
          assigned_at?: string;
          assigned_by?: string | null;
        };
        Relationships: [];
      };
      // Unchanged by Phase 1, but declared here so the team hooks can
      // read it through the same client rather than juggling two.
      project_roles: {
        Row: ProjectRoleRow;
        Insert: { id?: string; name: string };
        Update: { id?: string; name?: string };
        Relationships: [];
      };
      // Only the three columns Phase 3 touches. This is a narrowed view of
      // the real employees table, not a redefinition of it — the ordinary
      // typed client still sees the full row.
      employees: {
        Row: {
          id: string;
          department_id: string | null;
          specializations_id: string | null;
        };
        Insert: {
          id: string;
          department_id?: string | null;
          specializations_id?: string | null;
        };
        Update: {
          id?: string;
          department_id?: string | null;
          specializations_id?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      effective_permissions: {
        Args: { p_user_id: string; p_project_id?: string | null };
        Returns: EffectivePermissionRow[];
      };
      can_do: {
        Args: {
          p_user_id: string;
          p_permission_name: string;
          p_project_id?: string | null;
        };
        Returns: boolean;
      };
    };
    Enums: {
      party_type_enum: PartyType;
      grant_scope_enum: GrantScope;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
